publisher.first_name=Arno
publisher.last_name=Puder
publisher.email=mobile@puder.org
app.id=803144a0-d914-4eb1-a48e-1e9f30f0015f
app.name=BEAST
app.categories=GAME_ARCADE
app.version=1.0
app.year_published=2026
app.author=Steve Lewis
app.description=BEAST is a scaled-down clone of a game by the same name available on the
app.description=MS-DOS platform in 1984.  The goal is to squash all the beast using the blocks
app.description=spread out in the arena.  You can push the blocks (if no beast is near it)
app.description=or you can pull a block.  There are also eggs that will start to spawn, first
app.description=into infants and eventually in full beast.  The arena also has tree's, which
app.description=act as non-movable blocks.  The CMD tries to auto-detect M1 vs M3, and also
app.description=M1 7-bit vs 8-bit graphics.  If these are detected incorrectly, pressing M
app.description=at the start toggles M1/M3 mode, and T toggles 7-bit vs 8-bit symbols.
app.screenshot=BEAST_TRS_80_BOXART_1_6.jpg
app.screenshot=BEAST_M1_7BIT.JPG
app.screenshot=BEAST_TRS80_M1.jpg
app.screenshot=BEAST_TRS80_M3.jpg
app.platform=TRS-80
trs.model=MODEL_I
trs.image.disk=BEAST.DSK
trs.image.cmd=BEAST.CMD
