publisher.first_name=Tim
publisher.last_name=Walter
publisher.email=trs-80@tim-walter.net
app.id=96ac6b71-0e0f-4d2a-ba2e-ef208b9d9449
app.name=Space Invaders (Model III Edition)
app.categories=GAME_ARCADE
app.version=1.0
app.year_published=2026
app.author=Tim Walter
app.description=Inspired by Space Invaders, the first Arcade Game I played in my youth, and by
app.description=the great Big Five Games, which made my humble TRS-80 an Arcade Game console
app.description=and really showed what was possible. I enjoy playing it, hope you do too!
app.screenshot=screenshot1.png
app.screenshot=screenshot2.png
app.platform=TRS-80
trs.model=MODEL_III
trs.image.disk=disk_image.dsk
trs.image.cmd=SPACEINV.CMD
